#!/bin/bash

docker build -t alxprd/tts-festival -f docker/Dockerfile.festival ./docker

docker build -t alxprd/tts-espeak -f docker/Dockerfile.espeak ./docker

docker build -t alxprd/tts-pico -f docker/Dockerfile.picotts ./docker


